spring:
  profiles:
    active: local
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:        trace: false
        web-allow-others: false   datasource:    url: jdbc:h2:mem:testdb
logging:  level:    com.web: DEBUG
---
spring:
  profiles: local
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "client-id"
            client-secret: "client-secret"
          facebook:
            client-id: "client-id"
            client-secret: "client-secret"

custom:
  oauth2:
    kakao:
      client-id: "client-id"
            
server:
  port: 8080

---
spring:
  profiles: prd
server:
  port: 80
