spring:
  profiles:
    active: local
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:        trace: false
        web-allow-others: false   datasource:    url: jdbc:h2:mem:testdb
logging:  level:    com.web: DEBUG
---
spring:
  profiles: local
server:
  port: 8080  
---
spring:
  profiles: prd
server:
  port: 80
